global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'longin-core'
    static_configs:
      - targets: ['longin-core:3001']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
